#### **Importing Libraries**

In [4]:
import numpy as np
import pandas as pd

## **NumPy**
---

#### NumPy Array
- Works as any normal array/list

In [8]:
a = np.array([1, 2, 3])

##### Selecting multiple index from an array

In [10]:
a[[0, 2]]

array([1, 3])

##### Array Types

In [11]:
a.dtype

dtype('int64')

In [12]:
c = np.array([1, 2, 3], dtype=np.int8)
c.dtype

dtype('int8')

##### Dimensions and shapes

In [14]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [15]:
A.ndim

2

In [16]:
A.shape

(3, 3)

In [17]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [18]:
B.ndim

3

In [19]:
B.shape

(2, 2, 3)

##### Indexing and Slicing Matrix

In [20]:
A[0]

array([1, 2, 3])

In [21]:
A[1, 0]

4

In [22]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

#### Summary statistics

In [24]:
a.sum()

6

In [25]:
A.mean(axis=1)

array([2., 5., 8.])

#### Broadcasting and Vectorizing operations

In [26]:
a = np.arange(4) # [0, 1, 2, 3]

In [28]:
a + 10

array([10, 11, 12, 13])

In [29]:
a * 10

array([ 0, 10, 20, 30])

In [31]:
a += 10

In [32]:
a

array([20, 21, 22, 23])

### **Boolean Arrays**

In [33]:
a = np.arange(4)

In [34]:
a[[True, False, True, False]]

array([0, 2])

In [35]:
a >= 2

array([False, False,  True,  True])

In [36]:
a[a>=2]

array([2, 3])